version: "3.9"

services:
  database:
    restart: always
    container_name: simple-api-postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bnloYXNpbmE=
      - POSTGRES_db=simpleapi
    ports:
      - 5432:5432
    volumes:
      - api-db:/var/lib/postgresql/data

  api:
    container_name: simple-api
    build:
      context: .
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:bnloYXNpbmE=@database:5432/simpleapi?schema=public
    ports:
      - 3000:3000

volumes:
  api-db: